folder_in: /home/nameuser/tst
folder_out: /home/nameuserr/out
folder_ext: /home/nameuser/folder1
folder_ext2: /home/nameuser/folder2
count: 5
bs: 1M
ip: xxx.xxx.x.xxx
user: nameuser
passwd: "xxxxxxxxxx"
pkgname: p7zip-full
type: 7z
